name: delicat
description: The best way to catalogue your delicacies. Keep track of your cooking repertoir and expand you dish count.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  sqflite: ^1.3.0
  image_picker: ^0.6.5
  path_provider: ^1.6.5
  shared_preferences: ^0.5.7
  http: ^0.12.1
  flutter_colorpicker: ^0.3.4
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^1.0.2
  progress_indicators: ^0.1.5

  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/photos/breakfast.jpg
    - assets/photos/burgers.jpg
    - assets/photos/meat.jpg
    - assets/photos/mexican.jpg
    - assets/photos/pasta.jpg
    - assets/photos/pizza.jpg
    - assets/photos/rice.jpg
    - assets/photos/salads.jpg
    - assets/photos/turkish.jpg
    - assets/photos/veggies.jpg
    # logo
    - assets/logo/logo.png
    # circle-images
    - assets/photos/breakfast-circle.png
    - assets/photos/burgers-circle.png
    - assets/photos/dessert-circle.png
    - assets/photos/sushi-circle.png
    - assets/photos/pasta-circle.png
    - assets/photos/vegetable-circle.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
