name: delicat
description: The best way to catalogue your delicacies. Keep track of your cooking repertoir and expand you dish count.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
#  http: ^1.2.2
  flex_color_picker: ^3.5.1
  cupertino_icons: ^1.0.8
#  mime: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  progress_indicators: ^1.0.0
#  dio: ^5.7.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  auto_size_text: ^3.0.0
  tinycolor2: ^3.0.1
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Keys.json
    - assets/photos/breakfast.jpg
    - assets/photos/burgers.jpg
    - assets/photos/meat.jpg
    - assets/photos/mexican.jpg
    - assets/photos/pasta.jpg
    - assets/photos/pizza.jpg
    - assets/photos/rice.jpg
    - assets/photos/salads.jpg
    - assets/photos/turkish.jpg
    - assets/photos/veggies.jpg
    - assets/logo/logo.png
    - assets/photos/breakfast-circle.png
    - assets/photos/burgers-circle.png
    - assets/photos/dessert-circle.png
    - assets/photos/sushi-circle.png
    - assets/photos/pasta-circle.png
    - assets/photos/vegetable-circle.png
    - assets/photos/image1.png
